### ISSUE TITLE
Module 'ionic.utils' is not available! 

### ISSUE THREAD

**Issue by daruwanov** [sunsus/ngImgCache#1]
Hi! I try to use this your library. But after including module `ngImgCache`  in to my `app.js` file i have en error: 

`Module 'ionic.utils' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

Does this module required there? or it`s wrong?  It works fine for me with out this 'ionic.utils module.
As i understand it can work with out this in default using?.  I Create PR to remove this.

P.S Sorry for my english.

**Comment by mattezell** [comment]
+1 I agree that this should be pulled as well. It would appear that this likely came from the Ionic filesystem tutorial, in which they create a service named ionic.utils.  I do not see where any of the code from that tutorial module is required for the ngImgCache lib and remove it from the JS appears to resolve the error without side effect.

**Comment by sunsus** [comment]
Ok now there is a Ionic and non ionic version: 
https://github.com/sunsus/ngImgCache/blob/master/ngImgCache.js
